<!DOCTYPE html>
<html lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>PayUrFees</title>
	<link type="text/css" href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
	<link type="text/css" href="bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet">
	<link type="text/css" href="css/theme.css" rel="stylesheet">
	<link type="text/css" href="images/icons/css/font-awesome.css" rel="stylesheet">
	<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600' rel='stylesheet'>
</head>
<body>
<div >
<div class="wrapper" style="background:#042139; color:#FFFFFF;padding-top: 5px; padding-bottom: 5px">
		<div class="container">
			<div class="row">
            <div class="span12">Helpline : +91 0000000000 (10am to 6.30pm) <span  class="pull-right">&nbsp;&nbsp;<span style="color: #fff; font-weight: bold;">Email :</span> <a href="mailto:abcd@payurfees.com" style="color: #fff">abcd@payurfees.com</a></span></div>
            </div>
            </div>
            </div>

</div>
	<div class="navbar navbar-fixed-top" >
		<div class="navbar-inner">
                <div class="container">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".navbar-inverse-collapse">
                        <i class="icon-reorder shaded"></i></a><a class="brand" href="index.php"><img src="images/logo.png" alt="" /></a>
                    <div class="nav-collapse collapse navbar-inverse-collapse">
                        <ul class="nav nav-icons">
                        
                        
                       
                        
                            <!--<li class="active"><a href="#"><i class="icon-envelope"></i></a></li>
                            <li><a href="#"><i class="icon-eye-open"></i></a></li>
                            <li><a href="#"><i class="icon-bar-chart"></i></a></li>-->
                        </ul>
                       <!-- <form class="navbar-search pull-left input-append" action="#">
                        <input type="text" class="span3">
                        <button class="btn" type="button">
                            <i class="icon-search"></i>
                        </button>
                        </form>-->
                        
                    </div>
                    <!-- /.nav-collapse -->
                </div>
            </div><!-- /navbar-inner -->
	</div><!-- /navbar -->



	<div class="wrapper">
		<div class="container">
			<div class="row">
				<div class="module-login span4">
			<ul class="widget widget-menu unstyled">

                                <li class="active">		
<a href="ins_reg.php"><i class="menu-icon icon-plus"></i> Register your Institute.</a></li>
<li><a href="ins_log.php"><i class="menu-icon icon-user"></i> Login as Institute</a></li>
<li><a href="reg_parent.php"><i class="menu-icon icon-plus"></i> Register to Pay Fees.</a></li>
<li><a href="log_parent.php"><i class="menu-icon icon-refresh"></i> Pay Fees</a></li>
</ul>

				</div>
				
				<div class="module-login span6 offset1">
				
				<p style="font-size: 20px; color: #0067b3; padding-bottom: 5px;">Pay the easy & smart way</p>
				<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class='csslider1 autoplay '>
		<input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
		<input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
		<ul>
			<li class="cs_skeleton"><img src="cssslider_files/csss_images1/ban01.png" style="width: 100%;"></li>
			<li class='num0 img slide'> <img src='cssslider_files/csss_images1/ban01.png' alt='' title='' /></li>
			<li class='num1 img slide'> <img src='cssslider_files/csss_images1/ban02.png' alt='' title='' /></li>
			<li class='num2 img slide'> <img src='cssslider_files/csss_images1/ban03.png' alt='' title='' /></li>
		</ul><div class="cs_engine"><a href="http://cssslider.com">css slider</a> by cssSlider.com v2.1</div>
		
		<div class='cs_play_pause'>
			<label class='cs_play' for='cs_play1'><span><i></i><b></b></span></label>
			<label class='cs_pause num0' for='cs_pause1_0'><span><i></i><b></b></span></label>
			<label class='cs_pause num1' for='cs_pause1_1'><span><i></i><b></b></span></label>
			<label class='cs_pause num2' for='cs_pause1_2'><span><i></i><b></b></span></label>
			</div>
		<div class='cs_arrowprev'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_arrownext'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_bullets'>
			<label class='num0' for='cs_slide1_0'> <span class='cs_point'></span>
				</label>
			<label class='num1' for='cs_slide1_1'> <span class='cs_point'></span>
				</label>
			<label class='num2' for='cs_slide1_2'> <span class='cs_point'></span>
				</label>
		</div>
		</div>
		<!-- End cssSlider.com --></div>
				
			</div>
		</div>
	</div><!--/.wrapper-->

	<div class="footer">
            <div class="container">
                 <b class="copyright"><a href="index.php">Home</a>&nbsp;|&nbsp;<a href="#">About Us</a>&nbsp;|&nbsp;<a href="#">FAQ's</a>&nbsp;|&nbsp;<a href="#">Contact us</a> &nbsp;&nbsp;&nbsp;&nbsp;<br/>&copy; 2018 payurfees.com  </b> All rights reserved. |  &nbsp;Design by: <a href="http://www.websys.co.in" target="_blank" title="Website development company india">WEBSYS</a> <b class="pull-right">
                <a href="" target="_blank" title="Twitter"><i class="menu-icon icon-twitter"></i></a> &nbsp;&nbsp;
                <a href="" target="_blank" title="Facebook"><i class="menu-icon icon-facebook"></i></a>&nbsp;&nbsp;&nbsp;
                <a href="" target="_blank" title="Linkedin"><i class="menu-icon icon-linkedin"></i></a>&nbsp;&nbsp;&nbsp;
                <a href="" target="_blank" title="Youtube"><i class="menu-icon icon-play"></i></a></b>
            </div>
        </div>
        
        
	<script src="scripts/jquery-1.9.1.min.js" type="text/javascript"></script>
	<script src="scripts/jquery-ui-1.10.1.custom.min.js" type="text/javascript"></script>
	<script src="bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
</body>