<?php include("header.php");?>



	<div class="wrapper" style="padding-top:10px; padding-bottom:10px;">
		<div class="container" >
			<div class="row">
				
				
				<div class="module-login span6">
				
				
				<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class='csslider1 autoplay '>
		<input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
		<input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
		<ul>
			<li class="cs_skeleton"><img src="cssslider_files/csss_images1/ban01.png" style="width: 100%;"></li>
			<li class='num0 img slide'> <img src='cssslider_files/csss_images1/ban01.png' alt='' title='' /></li>
			<li class='num1 img slide'> <img src='cssslider_files/csss_images1/ban02.png' alt='' title='' /></li>
			<li class='num2 img slide'> <img src='cssslider_files/csss_images1/ban03.png' alt='' title='' /></li>
		</ul><div class="cs_engine"><a href="http://cssslider.com">css slider</a> by cssSlider.com v2.1</div>
		
		<div class='cs_play_pause'>
			<label class='cs_play' for='cs_play1'><span><i></i><b></b></span></label>
			<label class='cs_pause num0' for='cs_pause1_0'><span><i></i><b></b></span></label>
			<label class='cs_pause num1' for='cs_pause1_1'><span><i></i><b></b></span></label>
			<label class='cs_pause num2' for='cs_pause1_2'><span><i></i><b></b></span></label>
			</div>
		<div class='cs_arrowprev'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_arrownext'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_bullets'>
			<label class='num0' for='cs_slide1_0'> <span class='cs_point'></span>
				</label>
			<label class='num1' for='cs_slide1_1'> <span class='cs_point'></span>
				</label>
			<label class='num2' for='cs_slide1_2'> <span class='cs_point'></span>
				</label>
		</div>
		</div>
		<!-- End cssSlider.com --></div>


<div class="module-login span6 ">
			<h2 style="color: #0067b3;"><!--Pay the easy & smart way--><!--Aim of Payur fees-->About Us</h2>
			<p style="color: #000; font-weight: bold">Payurfees<sup>TM</sup> is a new venture of Synergic Softek Solutions Pvt. Ltd. in the field of Online Fee Collection and MIS Reporting Services. Synergic Softek Solutions Pvt. Ltd. is a common name in Cooperative Core Banking Software development landscape.</p>

<br><br/>
With years of experience and reputation in software development and customer service, Synergic Softek is entering in this new Software service area to cater to the need to streamlining the student fee collection process.It offers to enable both institutions and students enjoy the benefits for Queue-less, Stuff-less,Cash-less fee payment / collection system that operates 24/7.
<br/><br/>


<b>Payurfees<sup>TM</sup> </b> is an online fee payment solution designed for various types of educational institutions like schools,colleges& tutorial centers.
<br/><br/>
While students/parents can instantly pay all types of fees anytime, anywhere through their secured login id and password at the same time institutes gets a secured, digital & state of the art fee management solution.


		<!--	<ul>
				<li>Lorem Ipsum is simply dummy text of the printing </li>
				<li>Ipsum is simply dummy text of the printing </li>
				<li>Simply dummy text of the printing </li>
				<li>Lorem Ipsum is simply dummy text of  </li>
			</ul>-->
			 

				</div>
				
			</div>
		</div>
	</div><!--/.wrapper-->

<?php include("footer.php");?>