<?php include("header.php");?>



<body onLoad="Captcha();">




	<div class="wrapper" style="padding-top:1px; padding-bottom:1px;">
		<div class="container" >
			<div class="row">
				
				
<div class=" span12 ">
			<!--<h2 style="color: #0067b3;">Payurfees</h2>-->
            <!--<br>
                        <br><span style="font-size: 11px; color: #000; font-size: 24px;">The smartest way to pay fees</span>-->
			<p style="color: font-size:17px; padding-top:10px; color: #000"><b style="color: #0067b3;">Payurfees</b>
			
			
is an easy Digital Payment Solution for Schools, Colleges, Tutorial Centres, Universities and Other Educational Institutions as well as students & their parents for all types of fees
			
			
			
			
			<!-- is an online solution for the Educational Institutions as well as the Students
for all types of fee collection & payments, electronically-->.</p>
		<!--
			<a href="log_parent.php" style="color: #fff"><button class="btn btn-primary" style="font-size: 18px; padding: 10px 20px;">Pay Your Fees</button></a> &nbsp; <a href="log_parent.php" style="color: #fff"><button class="btn btn-primary" style="font-size: 18px; padding: 10px 20px;">View Demo</button></a>--> 

				</div>
				<div>&nbsp;</div>
				
				<div class=" span12">
				
				
				<!-- Start cssSlider.com -->
		<!-- Generated by cssSlider.com 2.1 -->
		<link rel="stylesheet" href="cssslider_files/csss_engine1/style.css">
		<!--[if IE]><link rel="stylesheet" href="cssslider_files/csss_engine1/ie.css"><![endif]-->
		<!--[if lte IE 9]><script type="text/javascript" src="cssslider_files/csss_engine1/ie.js"></script><![endif]-->
		 <div class='csslider1 autoplay '>
		<input name="cs_anchor1" id='cs_slide1_0' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_1' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_slide1_2' type="radio" class='cs_anchor slide' >
		<input name="cs_anchor1" id='cs_play1' type="radio" class='cs_anchor' checked>
		<input name="cs_anchor1" id='cs_pause1_0' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_1' type="radio" class='cs_anchor pause'>
		<input name="cs_anchor1" id='cs_pause1_2' type="radio" class='cs_anchor pause'>
		<ul>
			<li class="cs_skeleton"><img src="cssslider_files/csss_images1/ban01.png" style="width: 100%;"></li>
			<li class='num0 img slide'> <img src='cssslider_files/csss_images1/ban01.png' alt='' title='' /></li>
			<li class='num1 img slide'> <img src='cssslider_files/csss_images1/ban02.png' alt='' title='' /></li>
			<li class='num2 img slide'> <img src='cssslider_files/csss_images1/ban03.png' alt='' title='' /></li>
		</ul><div class="cs_engine"><a href="http://cssslider.com">css slider</a> by cssSlider.com v2.1</div>
		
		<div class='cs_play_pause'>
			<label class='cs_play' for='cs_play1'><span><i></i><b></b></span></label>
			<label class='cs_pause num0' for='cs_pause1_0'><span><i></i><b></b></span></label>
			<label class='cs_pause num1' for='cs_pause1_1'><span><i></i><b></b></span></label>
			<label class='cs_pause num2' for='cs_pause1_2'><span><i></i><b></b></span></label>
			</div>
		<div class='cs_arrowprev'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_arrownext'>
			<label class='num0' for='cs_slide1_0'><span><i></i><b></b></span></label>
			<label class='num1' for='cs_slide1_1'><span><i></i><b></b></span></label>
			<label class='num2' for='cs_slide1_2'><span><i></i><b></b></span></label>
		</div>
		<div class='cs_bullets'>
			<label class='num0' for='cs_slide1_0'> <span class='cs_point'></span>
				</label>
			<label class='num1' for='cs_slide1_1'> <span class='cs_point'></span>
				</label>
			<label class='num2' for='cs_slide1_2'> <span class='cs_point'></span>
				</label>
		</div>
		</div>
		<!-- End cssSlider.com --></div>

</div>
               <div class="row"> 
                
         <div class="span12 ">
    <h3 style="color:#006ab7; text-align: center; padding-bottom: 2px; margin-bottom: 0"><br>Can't find your Institute?</h3>
     <p align="center"><span style="color:#006ab7; font-size:15px; text-align: center; background: #8bc63e; padding: 2px 10px; margin-bottom: 5px;">Refer Here</span></p>
    </div>
    
    </div>
    
    	 <script type="text/javascript">
                 function Captcha(){
                     var alpha = new Array('A','B','C','D','E','F','G','H','I','J','K','L','M','N','O','P','Q','R','S','T','U','V','W','X','Y','Z','a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z');
                     var i;
                     for (i=0;i<6;i++){
                       var a = alpha[Math.floor(Math.random() * alpha.length)];
                       var b = alpha[Math.floor(Math.random() * alpha.length)];
                       var c = alpha[Math.floor(Math.random() * alpha.length)];
                       var d = alpha[Math.floor(Math.random() * alpha.length)];
                       var e = alpha[Math.floor(Math.random() * alpha.length)];
                       var f = alpha[Math.floor(Math.random() * alpha.length)];
                       var g = alpha[Math.floor(Math.random() * alpha.length)];
                      }
                    var code = a + ' ' + b + ' ' + ' ' + c + ' ' + d + ' ' + e + ' '+ f + ' ' + g;
                    document.getElementById("mainCaptcha").value = code
                  }
				  </script>
    <form class="form-horizontal row-fluid" action="mail_insadd.php" method="post" enctype="multipart/form-data" >


               <div class="row">
  <div class="span2 "><select name="ins_type" id="ins_type" style="width: 100%; margin-left: 3%" >
<option value="">--Institution Type--</option>
<option value="School">School</option>
<option value="College">College</option>
<option value="University">University</option>
<option value="Tutorial Center">Tutorial Center</option>
</select></div>	
    <div class="span2 "><input type="text" name="ins_name" id="ins_name" placeholder="Name of the Institution:" style="width: 96%" /></div>
    <div class="span2 "><input type="text" name="contact_person" id="contact_person" placeholder="Contact Person:" style="width: 96%"  /></div>
    <div class="span2 "><input type="text" name="mobile" id="mobile" placeholder="Contact No." style="width: 96%" /></div>
    
  
    <div class="span2 "><input type="text" id="mainCaptcha" readonly style="background:#FFCC33; color:#000000; width: 96%"/>
              <!--<input type="button" id="refresh" value="Refresh" onClick="Captcha();" placeholder="Captcha"" />--></div>
    <div class="span2 "><input type="text" id="txtInput" placeholder="Enter Code."  style="width: 96%"/></div>
    
    <div align="center" class="span12"><br><input type="submit" class="btn btn-primary btn-large" name="submit" id="submit" value="Submit" onClick="return test1();"/>
    <p>&nbsp;</p>
    </div>
    </div>
										
</form>

<script type="text/javascript" >

 function removeSpaces(string){
                    return string.split(' ').join('');
                  }
				  
				  
function test1()
{


if(document.getElementById('ins_name').value=='')
{
alert("Please enter the  Institute Name");
document.getElementById('ins_name').focus();
return false;
}

if(document.getElementById('ins_type').value=='')
{
alert("Please enter the  Institute Type");
document.getElementById('ins_type').focus();
return false;
}


if(document.getElementById('contact_person').value=='')
{
alert("Please enter the  Contact person Name");
document.getElementById('contact_person').focus();
return false;
}


if(document.getElementById('mobile').value=='')
{
alert("Please enter the Mobile No.");
document.getElementById('mobile').focus();
return false;
}
if(document.getElementById('mobile').value.length!='10')
{
alert("Please enter the  Mobile No 10 Digit No.");
document.getElementById('mobile').focus();
return false;
}	
	var mobexp1 =/^[0-9]+$/;
if (! document.getElementById('mobile').value.match(mobexp1))
{
alert("please enter number only for mobile feild");
 //document.getElementById('mobile').value='';
document.getElementById('mobile').focus();
return false ;
}

/*if(document.getElementById('email').value=='')
{
alert("Please enter the  Email Address");
document.getElementById('email').focus();
return false;
}
var oldemail=document.getElementById('email').value ;
	if(oldemail.split("@")==oldemail || oldemail.split(".")==oldemail)
	{
	alert("Please enter the correct email address");
	document.getElementById('email').focus();
	return false;
	}


if(document.getElementById('address').value=='')
{
alert("Please enter the  Institute Address");
document.getElementById('address').focus();
return false;
}
*/
if(document.getElementById('txtInput').value=='')
{
  alert("Please enter the   capcha code");
document.getElementById('txtInput').focus();
                        return false;
}
  var string1 = removeSpaces(document.getElementById('mainCaptcha').value);
                      var string2 = removeSpaces(document.getElementById('txtInput').value);
                      if (string1 != string2)
					  {
					  alert("Please enter the  Valid capcha code");
document.getElementById('txtInput').focus();
                        return false;
                      }
                  

return true;
}
</script>


    
    
  
    
				
			</div>
			
			
			
			
			
		</div>
        
        
       
    
    
	</div><!--/.wrapper-->
    
    
            
    

	<?php include("footer.php");?>